[package]
name = "release-the-launcher-net"
version = { workspace = true }
edition = "2021"
description = "HTTP downloads, caching, checksum validation"
license.workspace = true

[dependencies]
reqwest    = { workspace = true }
sha2       = "0.10"
sha1       = "0.10"
tokio      = { workspace = true, features = ["fs", "io-util"] }
serde      = { workspace = true }
serde_json = { workspace = true }
thiserror  = { workspace = true }
hex        = { workspace = true }
tracing    = { workspace = true }
release-the-launcher-constants = { path = "../constants" }
