[package]
name = "release-the-launcher-launch"
version = { workspace = true }
edition = "2021"
description = "Version resolution, dependency graph, Java launch"

[dependencies]
release-the-launcher-net = { path = "../net" }
release-the-launcher-constants = { path = "../constants" }
release-the-launcher-core = { path = "../core" }
reqwest = { version = "0.12.28", features = ["json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "process", "sync", "macros"] }
thiserror = "2"
version-compare = "0.2"
quick-xml = { version = "0.41", features = ["serialize"] }
zip = "8.6.0"
dirs = "5"
tracing = "0.1"
sysinfo = "0.39"


[dev-dependencies]
tempfile = "3"

[target.'cfg(windows)'.dependencies]
winreg = "0.52"
