[package]
name = "release-the-launcher-ui"
version = { workspace = true }
edition = "2021"
description = "egui-based UI, views only"
license.workspace = true

[dependencies]
release-the-launcher-core = { path = "../core" }
release-the-launcher-auth = { path = "../auth" }
release-the-launcher-mods = { path = "../mods" }
release-the-launcher-coordinator = { path = "../coordinator" }
egui = "0.27"
egui-phosphor = "0.5"
eframe = "0.27"
rfd = "0.12"
egui_extras = { version = "0.27", features = ["all_loaders"] }
image = { version = "0.24", features = ["webp"] }
open = "5"
