[package]
name = "release-the-launcher-ui"
version = "0.4.1"
edition = "2021"
description = "egui-based minimal UI"

[dependencies]
release-the-launcher-core = { path = "../core" }
release-the-launcher-auth = { path = "../auth" }
release-the-launcher-net = { path = "../net" }
release-the-launcher-mods = { path = "../mods" }
release-the-launcher-launch = { path = "../launch" }
egui = "0.27"
egui-phosphor = "0.5"
eframe = "0.27"
rfd = "0.12"
poll-promise = "0.3"
tokio = { version = "1", features = ["full"] }
thiserror = "1"
dirs = "5"
egui_extras = "0.27"
tracing = "0.1"
tracing-subscriber = "0.3"
chrono = "0.4"
open = "5"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
