[package]
name = "release-the-launcher-mods"
version = { workspace = true }
edition = "2021"
description = "Mod provider trait, Modrinth implementation"
license.workspace = true

[dependencies]
reqwest     = { workspace = true, features = ["stream", "json"] }
serde       = { workspace = true }
serde_json  = { workspace = true }
zip         = { workspace = true }
async-trait = { workspace = true }
thiserror   = { workspace = true }
toml        = { workspace = true }
tokio       = { workspace = true, features = ["sync", "rt", "macros"] }
log         = "0.4"
release-the-launcher-constants = { path = "../constants" }
release-the-launcher-core      = { path = "../core" }
release-the-launcher-net       = { path = "../net" }
