[package]
name = "release-the-launcher-core"
version = { workspace = true }
edition = "2021"
description = "Instance model, filesystem, settings, archive extraction"
license.workspace = true

[dependencies]
serde      = { workspace = true }
toml       = { workspace = true }
zip        = { workspace = true }
thiserror  = { workspace = true }
sha1       = "0.10"
hex        = { workspace = true }
release-the-launcher-constants = { path = "../constants" }
